[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-web = "4.4.0"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.189", features = ["derive"]}
config = "0.13.3"
uuid = { version = "1.5.0", features = ["v4"]}
chrono = "0.4.31"

[dependencies.sqlx]
version = "0.7.2"
default-features = false
features = [
    "macros",
    "postgres",
    "uuid",
    "chrono",
    "migrate",
    "runtime-tokio"
]

[dev-dependencies]
reqwest = "0.11.22"
rstest = "0.18.2"