database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  db_name: "newsletter"
app:
  port: 8080
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  secret: "secret"
  timeout_ms: 10000